### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by midnit3Z0mbi3** [owasp-amass/amass#1019]
Hello, I am using the most current version of amass, go package v4.2.0, and I am using the example config.yaml file with the datasources.yaml file. I am also using a resolver.txt file that was suggested by other users. 

I am able to get amass to use my config and datasources, but ONLY without the postgresql entry.

I created a user and a database for amass, but when I use it in my config I get the following error

panic: ERROR: operator class "gin_trgm_ops" does not exist for access method "gin" (SQLSTATE 42704) handling 005_assets_indexes.sql
goroutine 1 [running]:
github.com/caffix/netmap.NewGraph({0xc0001fcb90?, 0x2d?}, {0xc008c7a5f0?, 0x5?}, {0x5?, 0xc000697448?})
    /home/osint/go/pkg/mod/github.com/caffix/netmap@v0.2.5/graph.go:91 +0x44c
github.com/owasp-amass/amass/v4/systems.(*LocalSystem).setupGraphDBs(0xc0001cc2a0, 0xc0003b8540)
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/systems/local.go:227 +0x317
github.com/owasp-amass/amass/v4/systems.NewLocalSystem(0xc0003b8540)
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/systems/local.go:86 +0x2bb
main.GetAllSourceInfo(0x0?)
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/cmd/amass/main.go:127 +0x4f
main.argsAndConfig({0xc000040b30, 0x1, 0x1})
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/cmd/amass/enum.go:332 +0xa8f
main.runEnumCommand({0xc000040b30?, 0xc000040b20?, 0xc0002fc3d0?})
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/cmd/amass/enum.go:150 +0x38
main.main()
    /home/osint/go/pkg/mod/github.com/owasp-amass/amass/v4@v4.2.0/cmd/amass/main.go:110 +0x2f2

**Comment by midnit3Z0mbi3** [comment]
sorry, i changed the issue because  I was able to get amass to run, but only when i comment out the postgresql entry.

I am using v4.2.0. 

When i use the postgresql entry of the config.yaml i get the following error. 
panic: ERROR: operator class "gin_trgm_ops" does not exist for access method "gin" (SQLSTATE 42704) handling 005_assets_indexes.sql

**Comment by midnit3Z0mbi3** [comment]
I ended up commenting out the postgresql entry and Amass worked fine.
